version: "3.4"

networks:
  isfa-network:
    driver: bridge

services:

  identityserver:
    container_name: isfa-identityserver
    image: isfa/identityserver
    restart: always
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001
      ASPNETCORE_HTTPS_PORT: 5001
      IssuerUri: https://identityserver
    ports:
      - 5001:5001
    networks:
      - isfa-network
    volumes:
      - ~/.aspnet/https:/https:ro
